name: Deploy to Server

on:
  push:
    branches:
      - main # Workflow akan berjalan otomatis setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }} # Biasanya port 22
          command_timeout: 60m
          script: |
            if [ -d /var/www/be-UrbanDensityMonitor/.git ]; then
              cd /var/www/be-UrbanDensityMonitor
              git pull origin main
            else
              echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S mkdir -p /var/www
              echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S chown -R $USER:$USER /var/www
              git clone https://github.com/Mahdanaa/be-UrbanDensityMonitor.git /var/www/be-UrbanDensityMonitor
              cd /var/www/be-UrbanDensityMonitor
            fi
            
            # Buat file .env secara otomatis dari GitHub Secrets
            echo "${{ secrets.APP_ENV }}" > /var/www/be-UrbanDensityMonitor/.env
            
            cd docker
            docker compose down
            # Bersihkan sistem docker lama agar disk tidak penuh
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker system prune -af
            docker compose up -d --build
